services:
  db:
    container_name: db
    image: mysql:8.2.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: quarkus2
      MYSQL_ROOT_PASSWORD: rootrootroot
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    links:
      - db