###
###POST http://140.238.216.80:8080/lobby

###
###GET http://140.238.216.80:8080/lobby/UoGVzm

### Tests for endpoints
@url=http://localhost:8080/lobby

### Test for adding a Lobby
POST {{url}}

### Test for getting a Lobby by LobbyId
GET {{url}}/zNcvrl

### Test for adding a GameState
POST {{url}}/nGDbCK/gameState
Content-Type: application/json

{
  "currentRoomId": 1,
  "currentChallengeId": 1
}

### Test for getting a GameState
GET {{url}}/AZMiiL/gameState

### Test for adding a Challenge
POST {{url}}/challenge
Content-Type: application/json

{
  "name": "Challenge",
  "description": "Description",
  "hint": "Hint"
}

### Test for adding a Diary Entry
POST {{url}}/diary
Content-Type: application/json

{
  "challengeId": 1,
  "chapter": "Kapitel 1",
  "entry": "Text"
}