services:
  db:
    container_name: db
    image: mysql:8.2.0
    ports:
      - "3306:3306"
      - "33060:33060"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: quarkus2
      MYSQL_ROOT_PASSWORD: rootrootroot
      
  frontend:
    container_name: frontend
    image: sophieboehm/frontend:latest
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
  backend:
    container_name: backend
    image: sophieboehm/backend:latest
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    links:
      - db